ControllerParameterBindExample/Models/MyModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ControllerParameterBindExample.Models
{
    public class MyModel
    {
        public int? Property1 { get; set; }
        public int? Property2 { get; set; }
        public int? Property3 { get; set; }
        public int? Property4 { get; set; }
        public int? Property5 { get; set; }

    }
}

ControllerParameterBindExample/Controllers/MyModelController.cs
using ControllerParameterBindExample.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControllerParameterBindExample.Controllers
{
    public class MyModelController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        #region Default Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(MyModel model)
        {
            SetViewBagFromModel(model);

            return View();
        }
        #endregion

        #region Create Black Listing Property
        [HttpGet]
        public ActionResult CreateWithBindingExclude()
        {
            return View("Create");
        }

        [HttpPost]
        public ActionResult CreateWithBindingExclude([Bind(Exclude="Property1, Property2")]MyModel model)
        {
            SetViewBagFromModel(model);
            return View("Create");
        }
        #endregion

        #region Create White Listing Property

        [HttpGet]
        public ActionResult CreateWithBindingInclude()
        {
            return View("Create");
        }

        [HttpPost]
        public ActionResult CreateWithBindingInclude([Bind(Include = "Property1, Property2")]MyModel model)
        {
            SetViewBagFromModel(model);
            return View("Create");
        }
        #endregion

        private void SetViewBagFromModel(MyModel model)
        {
            ViewBag.Prop1 = model.Property1;
            ViewBag.Prop2 = model.Property2;
            ViewBag.Prop3 = model.Property3;
            ViewBag.Prop4 = model.Property4;
            ViewBag.Prop5 = model.Property5;
        }

	}
}

ControllerParameterBindExample/Views/MyModel/Create.cshtml
@model ControllerParameterBindExample.Models.MyModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MyModel</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Property1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Property1)
                @Html.ValidationMessageFor(model => model.Property1)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property2, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Property2)
                @Html.ValidationMessageFor(model => model.Property2)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property3, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Property3)
                @Html.ValidationMessageFor(model => model.Property3)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property4, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Property4)
                @Html.ValidationMessageFor(model => model.Property4)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property5, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Property5)
                @Html.ValidationMessageFor(model => model.Property5)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <h3>View Bag Result from binding</h3>
    <ul>
        <li>@ViewBag.Prop1</li>
        <li>@ViewBag.Prop2</li>
        <li>@ViewBag.Prop3</li>
        <li>@ViewBag.Prop4</li>
        <li>@ViewBag.Prop5</li>
    </ul>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ControllerParameterBindExample/Views/MyModel/Index.cshtml
@model IEnumerable<ControllerParameterBindExample.Models.MyModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Property1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Property2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Property3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Property4)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Property5)
        </th>
        <th></th>
    </tr>
@if(Model!=null)
{ 
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Property1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Property2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Property3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Property4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Property5)
            </td>
        </tr>
    }
}
</table>

ControllerParameterBindExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("MyModel Create Without Binding", "Create", "MyModel")</li>
                    <li>@Html.ActionLink("MyModel Create With Binding", "CreateWithBinding", "MyModel")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>